apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotdb-chart.fullname" . }}-external
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-bp1siulzeqxfx1hm45zru 
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"    
  labels:
    {{- include "iotdb-chart.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp-9092
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    {{- include "iotdb-chart.selectorLabels" . | nindent 4 }}
  type: LoadBalancer