apiVersion: v1
kind: Service
metadata:
  name: iotdb-confignode-external
  labels:
    {{- include "iotdb-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: tcp-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    {{- include "iotdb-chart.selectorLabels" . | nindent 4 }}
  clusterIP: LoadBalancer
  type: {{ .Values.service.type }}
