apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: bisheng-zxp
  labels:
    app: milvus-etcd
  name: milvus-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-etcd
  template:
    metadata:
      labels:
        app: milvus-etcd
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: container-qecx8k
          imagePullPolicy: IfNotPresent
          image: 'cr.dataelem.com/quay.io/coreos/etcd:v3.5.5'
          ports:
            - name: http-2379
              protocol: TCP
              containerPort: 2379
              servicePort: 2379
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: '1000'
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: '4294967296'
            - name: ETCD_SNAPSHOT_COUNT
              value: '50000'
          volumeMounts:
            - readOnly: false
              mountPath: /etcd
              name: milvus-etcd
          command:
            - etcd
          args:
            - '-advertise-client-urls=http://0.0.0.0:2379' 
            - '-listen-client-urls=http://0.0.0.0:2379'
            - '--data-dir=/etcd'
      serviceAccount: default
      initContainers: []
      volumes: []
      imagePullSecrets: null
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  serviceName: milvus-etcd-01io
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: external-default-sc
      metadata:
        name: milvus-etcd
        namespace: bisheng-zxp
---
apiVersion: v1
kind: Service
metadata:
  namespace: bisheng-zxp
  labels:
    app: milvus-etcd
  name: milvus-etcd-01io
  annotations:
    kubesphere.io/alias-name: milvus-etcd
    kubesphere.io/serviceType: statefulservice
spec:
  sessionAffinity: None
  selector:
    app: milvus-etcd
  ports:
    - name: http-2379
      protocol: TCP
      port: 2379
      targetPort: 2379
  clusterIP: None


