apiVersion: v1
kind: ConfigMap
metadata:
  labels: {}
  name: bisheng-mysql-cnf #配置名称 
spec:
  template:
    metadata:
      labels: {}
data:
  my.cnf: >-
    [client]

    default-character-set=utf8mb4


    [mysql]

    default-character-set=utf8mb4


    [mysqld]

    init_connect='SET collation_connection = utf8mb4_unicode_ci, NAMES utf8mb4'

    character-set-server=utf8mb4

    collation-server=utf8mb4_unicode_ci

    # skip-character-set-client-handshake

    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION


