apiVersion: v1
data:
  pg_hba.conf: |-
    host     all             all             0.0.0.0/0               md5
    host     all             all             ::1/128                 md5
    local    all             all                                     md5
  postgresql.conf: |-
    listen_addresses = '*'
    port = '5432'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kong
    meta.helm.sh/release-namespace: default
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: Helm
    chart: postgresql-8.6.8
    heritage: Helm
    release: kong
  name: kong-postgresql-configuration
  namespace: default
