apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-pg-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-disk-topology-alltype
  volumeMode: Filesystem
