apiVersion: v1
data:
  postgresql-password: a29uZw==
kind: Secret
metadata:
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: Helm
    chart: postgresql-8.6.8
    heritage: Helm
    release: kong
  name: kong-postgresql
  namespace: default
type: Opaque
